[package]
name = "eml_parser"
version = "0.2.2"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
mailparse = "0.14"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
colored = "2.0"